// Mocks generated by Mockito 5.4.2 from annotations
// in test_app/test/widget_album_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_app/models/album.dart' as _i2;
import 'package:test_app/services/impl/album_service_impl.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAlbum_0 extends _i1.SmartFake implements _i2.Album {
  _FakeAlbum_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AlbumServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlbumServiceImpl extends _i1.Mock implements _i3.AlbumServiceImpl {
  @override
  _i4.Future<_i2.Album> fetchAlbum(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchAlbum,
          [id],
        ),
        returnValue: _i4.Future<_i2.Album>.value(_FakeAlbum_0(
          this,
          Invocation.method(
            #fetchAlbum,
            [id],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Album>.value(_FakeAlbum_0(
          this,
          Invocation.method(
            #fetchAlbum,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Album>);

  @override
  _i4.Future<List<_i2.Album>> fetchListAlbum() => (super.noSuchMethod(
        Invocation.method(
          #fetchListAlbum,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Album>>.value(<_i2.Album>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Album>>.value(<_i2.Album>[]),
      ) as _i4.Future<List<_i2.Album>>);
}
